copy ..\AbortException.java .
copy ..\ArrowTurtle.java .
copy ..\BallTurtle.java .
copy ..\BoxTurtle.java .
copy ..\CrossTurtle.java .
copy ..\DiamondTurtle.java .
copy ..\Params.java .
copy ..\PixelRectangle.java .
copy ..\Sprite.java .
copy ..\SpritePixels.java .
copy ..\TGArcOp.java .
copy ..\TGCanvas.java .
copy ..\TGFillOp.java .
copy ..\TGGraphicsOp.java .
copy ..\TGKeyHandler.java .
copy ..\TGLabelOp.java .
copy ..\TGLineOp.java .
copy ..\TGMouseHandler.java .
copy ..\TGPoint.java .
copy ..\TGSetPixelsOp.java .
copy ..\TriangleTurtle.java .
copy ..\TurtleTurtle.java .
copy ..\UserTurtle.java .
